### ISSUE TITLE
Event page broken - HTTP 500

### ISSUE THREAD

**Issue by bjwo** [criticalmass-one/criticalmass-in#440]
a GPX track was uploaded for the following event. The upload resulted in a HTTP 500 error. However, looking at the https://criticalmass.in/ start page, I can see that the track was successfully uploaded and rendered for the event.

However, now the event page cannot be opened anymore and always results in a HTTP 500 error: https://criticalmass.in/mannheim/2019-04-19

Can you kindly look at this?

Thanks
Björn

**Comment by maltehuebner** [comment]
Hej Björn,

thanks for your report. The problem was caused by a broken upload function and the event page tried to generate a static map image with that half-uploaded track file which caused the error 500.

It should hopefully be fixed in #447.

Thanks
Malte

**Comment by bjwo** [comment]
Hi Malte, something still isn't quite right. Currently, I cannot open our city overview page at all: https://criticalmass.in/mannheim Can you kindly look into this again? Many thanks, Björn

**Comment by maltehuebner** [comment]
There was an issue regarding markdown stuff two years ago and it looks like I fixed it, but did miss any notifications about your reply here, bjwo :-(
