### ISSUE TITLE
Unable to add new cities

### ISSUE THREAD

**Issue by soraaerial** [criticalmass-one/criticalmass-in#923]
Am I correct to assume that as the site is locked there adding of new cities is too?

**Comment by maltehuebner** [comment]
@soraaerial You should be able to add new cities after a registration.

**Comment by soraaerial** [comment]
Hi @maltehuebner i realised the issue. 

When there are no states listed for a country, one cannot see the add city button. 

Australia has no States listed so that is why. 

Would you be able to add the states for Australia to the database please?

**Comment by soraaerial** [comment]
Sorry, didnt mean to close. 

Any help would be great. Thanks!

**Comment by ahokcool** [comment]
Hey there,

same for Portugal. @maltehuebner would be awesome if you could add the following states to the country portugal:

**Districts**
Aveiro
Beja
Braga
Bragança
Castelo Branco
Coimbra
Évora
Faro
Guarda
Leiria
Lisboa
Portalegre
Porto
Santarém
Setúbal
Viana do Castelo
Vila Real
Viseu
Azoren
Madeira

Lisboa is atm located in "Niedersachsen" and this sounds wrong to me ;)

![germany](https://github.com/criticalmass-one/criticalmass-in/assets/114107898/5fe419af-dfbc-4b36-bc7e-b76cff1bacb6)

**Comment by foss-** [comment]
Seems fixed with https://github.com/criticalmass-one/criticalmass-in/pull/997 Thanks so much @maltehuebner 
Lisboa also located in Portugal by now.
@legofahrrad could you retry adding your city and report back if that worked?

Can this issue be closed?

**Comment by ahokcool** [comment]
> Seems fixed with https://github.com/criticalmass-one/criticalmass-in/pull/997 Thanks so much @maltehuebner 
> Lisboa also located in Portugal by now.
> @legofahrrad and @soraaerial could you retry adding your city and report back if that worked?
> 
> Can this issue be closed?

Portugal still doesn't have Districts 🫠 
I just moved Lisbon to Spain since it does make more sense than Germany :D 

![image](https://github.com/user-attachments/assets/3863834e-39ed-4e35-a45b-fa1649eb58b6)

**Comment by foss-** [comment]
Ok that should probably be it's own follow-up issues, since adding cities in general was broken and that should be functional again.

**Comment by ahokcool** [comment]
> Ok that should probably be it's own follow-up issues, since adding cities in general was broken and that should be functional again.

Adding cities works - adding districts doesn't :)
